commerce_payment.commerce_payment_gateway.plugin.klarna_checkout:
  type: commerce_payment_gateway_configuration
  mapping:
    username:
      type: string
      label: 'Username'
    password:
      type: string
      label: 'Password'
    locale:
      type: string
      label: 'Language'
    terms_path:
      type: path
      label: 'Terms path'
    update_billing_profile:
      type: boolean
      label: 'Update billing profile'
